#ifndef _AL_GLOBAL_H_
#define _AL_GLOBAL_H_

typedef struct CHAO_GLOBAL {
    int CalcBuyo;
    int DispWorldEntry;
    int DispOnScreen;
    int DispScreenFrame;
    int DispField;
    Uint16 InitMulPotentialSkill;
    Uint16 InitBaseLife;
    Uint16 InitMulLife;
    Uint16 InitMulForm;
    Uint16 InitMulAttr;
    float WalkAcc;
    float WalkSlowAcc;
    float RunAcc;
    float BoundFriction;
    float BoundFloor;
    Uint16 SkillLimit;
    Uint16 LifeMaxLimit;
    Sint8 EmotionMoodLimit;
    Uint16 EmotionStateLimit;
    Sint8 EmotionPersonalityLimit;
    float DeformLimit;
    float GrowthLimit;
    float GrowthMayuPoint;
    float NormalBoundary;
    float NeutralBoundary;
    float AddGrowthTime;
    float TimeAddGrowthChild;
    float TimeAddGrowthAdult;
    float TimeAddAttrChild;
    float TimeAddAttrAdult;
    float PartsSetProb;
    float PartsRemoveProb;
    float CamDistShadowCutLev1;
    float CamDistShadowCutLev2;
    float CamDistShadowCutLev3;
    float CamDistShadowCutLev4;
    float CamDistShadowCutLev5;
    unsigned int MayuWaitTime;
    unsigned int MayuFadeInTime;
    unsigned int MayuTypeChageTime;
    unsigned int MayuFadeOutTime;
    unsigned int MayuRelaxTime;
    float MayuExpandRatio;
    float MayuShrinkRatio;
    float MayuInitAlpha;
    Sint16 SucceedBoundaryUserLike;
    Uint16 SucceedBoundaryStress;
    Uint16 SucceedBoundaryCondition;
    Uint16 SucceedBoundaryMood;
    float FruitAddGrowthChild;
    float FruitAddGrowthAdult;
    Uint16 FruitAddStaminaChild;
    Uint16 FruitAddStaminaAdult;
    int FruitAddRecoverLife;
    int FruitAddLifeMax;
    int FruitAddUserLike;
    float FruitAddAttrChild;
    float FruitAddAttrAdult;
    float FruitDislikeSubAttr;
    float FruitPakuriSubAttr;
    float MinimalAddFormChild;
    float MinimalAddFormAdult;
    float MinimalAddAttrChild;
    float MinimalAddAttrAdult;
    float MinimalAddGrowthChild;
    float MinimalAddGrowthAdult;
    int MinimalAddUserLike;
    float DakkoAddAttr;
    float DamageSubAttr;
    float NadeAddAttr;
    float ThrownSubAttr;
    int DamageAddLife;
    int DamageAddLifeMax;
    Uint16 NestFlowerInterval;
    Uint16 nbNestFlower;
    float NestRange;
    Uint16 NestWaitTime;
    Uint16 SeedClock;
    Uint16 SaplingClock;
    Uint16 TreeClock;
    Uint16 WaterSub;
    float TreeFruitAddGrowth;
    Uint16 FruitMaxNum;
    Uint16 KwSubFear;
    Uint16 KwAddDistance;
    Uint16 SkillWalk;
    Uint16 SkillRun;
    Uint16 SkillRun2;
    float SkillRunAccBase;
    float SkillRunAccRatio;
    Uint16 SkillSwimInukaki;
    Uint16 SkillSwimBataashi;
    Uint16 SkillSwimCrawl;
    float SkillSwimAccBase;
    float SkillSwimAccRatio;
    Uint16 ParamSubPleasure;
    Uint16 ParamSubAnger;
    Uint16 ParamSubSorrow;
    Uint16 ParamSubFear;
    Uint16 ParamSubSurprise;
    Uint16 ParamSubPain;
    Uint16 ParamSubRelax;
    Uint16 ParamAddSleepy;
    Uint16 ParamSubSleepy;
    Uint16 ParamAddSleepDepth;
    Uint16 ParamSubSleepDepth;
    Uint16 ParamWakeUpSleepDepth;
    Uint16 ParamAddHunger;
    Uint16 ParamSubHunger;
    Uint16 ParamAddBreed;
    Uint16 ParamAddTediousCuriosity;
    Uint16 ParamAddTediousAggressive;
    Uint16 ParamAddTediousCalm;
    Uint16 ParamSubTediousWalk;
    Uint16 ParamSubTediousSwim;
    Uint16 ParamAddLonely;
    Uint16 ParamAddLonelyGreet;
    Uint16 ParamAddLonelySuri;
    Uint16 ParamAddLonelyAttack;
    Uint16 ParamAddTireNormal;
    Uint16 ParamSubTireSleep;
    Uint16 ParamSubTireRest;
    Uint16 ParamAddTireWalk;
    Uint16 ParamAddTireRun;
    Uint16 ParamAddTireSwim;
    Uint16 ParamSubTireSwimStop;
    Uint16 ParamSubNourishment;
    Uint16 ParamAddConditionN;
    Uint16 ParamConditionTriggerAddN;
    Uint16 ParamSubConditionN;
    Uint16 ParamConditionTriggerSubN;
    Uint16 ParamSubConditionS;
    Uint16 ParamConditionTriggerS;
    Uint16 ParamSubConditionP;
    Uint16 ParamConditionTriggerP;
    Uint16 ParamAddConditionRest;
    Uint16 ParamAddThirsty;
    Uint16 ParamSubThirstySwim;
    Uint16 ChaoTimerBaseInterval;
    Uint16 ChaoTimerLifeInterval;
    Uint16 ChaoTimerEmotionInterval;
    Uint16 ChaoTimerMoodInterval;
    Uint16 ChaoTimerKnowledgeInterval;
    Uint16 ChaoTimerIllInterval;
    float IntentionScoreRandomRatio;
    float IntentionMinScore;
    unsigned int IntentionAngerTrigger;
    unsigned int IntentionAngerPlayerTrigger;
    float IntentionAngerMinScore;
    float IntentionAngerMaxScore;
    unsigned int IntentionFearTrigger;
    unsigned int IntentionFearPlayerTrigger;
    float IntentionFearMinScore;
    float IntentionFearMaxScore;
    unsigned int IntentionSorrowTrigger;
    float IntentionSorrowMinScore;
    float IntentionSorrowMaxScore;
    unsigned int IntentionPainTrigger;
    float IntentionPainMinScore;
    float IntentionPainMaxScore;
    unsigned int IntentionPleasureTrigger;
    float IntentionPleasureMinScore;
    float IntentionPleasureMaxScore;
    unsigned int IntentionHungerGooMinInterval;
    unsigned int IntentionHungerGooIntervalRange;
    unsigned int IntentionHungerGooTrigger;
    float IntentionHungerGooMaxScore;
    unsigned int IntentionHungerFruitGoToEatTrigger;
    float IntentionHungerFruitGoToEatMaxScore;
    unsigned int IntentionHungerFruitSearchTrigger;
    float IntentionHungerFruitSearchMaxScore;
    unsigned int IntentionAkubiMinInterval;
    unsigned int IntentionAkubiIntervalRange;
    unsigned int IntentionAkubiTrigger1;
    unsigned int IntentionAkubiTrigger2;
    unsigned int IntentionAkubiTrigger3;
    float IntentionAkubiMaxScore;
    unsigned int IntentionPlayerGreetLonelyTrigger;
    float IntentionPlayerGreetMaxScore;
    unsigned int IntentionPlayerSuriSuriLonelyTrigger;
    float IntentionPlayerSuriSuriMaxScore;
    unsigned int IntentionSleepTrigger;
    float IntentionSleepMaxScore;
    unsigned int IntentionHimaTrigger;
    float IntentionHimaMaxScore;
    unsigned int IntentionThirstyTrigger;
    float IntentionThirstyMaxScore;
    unsigned int IntentionApproachNestTrigger;
    float IntentionApproachNestMaxScore;
    unsigned int IntentionJyouroThirstyTrigger;
    float IntentionJyouroMaxScore;
    unsigned int IntentionRestTrigger1;
    unsigned int IntentionRestTrigger2;
    float IntentionRestMaxScore;
    unsigned int IntentionRestEndTrigger;
    unsigned int RaceIntervalSubStamina;
    unsigned int RaceSubStaminaSwim;
    unsigned int RaceSubStaminaFly;
    unsigned int RaceSubStaminaRun;
    unsigned int RaceSubStaminaClimb;
    unsigned int RaceSubStaminaTree;
    unsigned int RaceSubStaminaOther;
    unsigned int RaceAddStaminaSit;
    unsigned int RaceCheerInterval;
    unsigned int RaceCheerDecAimStamina;
    unsigned int RaceCheerDecStamina;
    float RaceTurboRatioSwim;
    float RaceTurboRatioFly;
    float RaceTurboRatioRun;
    float RaceTurboRatioClimb;
    float RaceTurboRatioTree;
    float RaceTurboRatioOther;
} CHAO_GLOBAL;

extern CHAO_GLOBAL ChaoGlobal;
#define GET_GLOBAL() (&ChaoGlobal)

#endif