#ifndef _AL_TEXLIST_H_
#define _AL_TEXLIST_H_

#include <ninja.h>

extern NJS_TEXLIST AL_BODY_TEXLIST;
extern NJS_TEXLIST AL_JEWEL;
extern NJS_TEXLIST AL_ENV_TEX;
extern NJS_TEXLIST AL_MOUTH;
extern NJS_TEXLIST AL_EYE;
extern NJS_TEXLIST AL_MINI_PARTS_TEX;
extern NJS_TEXLIST AL_ICON_TEXLIST;
extern NJS_TEXLIST off_C5FFDEC;
extern NJS_TEXLIST AL_OBJECT_TEXLIST;
extern NJS_TEXLIST AL_TOY_TEXLIST;

#endif
